import type { JobInput } from "~/lib/schemas/job";

const now = new Date()

export const mockData: JobInput[] = [
  {
    id: "27672077-d65a-4e1b-af8a-4802bc6a0ec6",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 1,
    name: "cumque dolore et",
    accountName: "Casper LLC",
    status: "measure",
    total: 633.00,
    date: now,
    address: {
      street: "Kacey Meadows",
      city: "Fort Tressieland",
      state: "Alaska",
      zip: "58185",
    },
  },
  {
    id: "a33bab25-f942-4b02-a37c-8f9009fb91cc",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 2,
    name: "corporis laborum non",
    accountName: "Stark Industries",
    status: "install",
    total: 123.00,
    date: now,
    address: {
      street: "Dawson Rest",
      city: "South Finnworth",
      state: "Massachusetts",
      zip: "18135",
    },
  },
  {
    id: "2412370c-c023-43df-9ee1-11dbcf3f15a4",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 3,
    name: "quia eaque quisquam",
    accountName: "Wayne Enterprises",
    status: "fabricate",
    total: 840.00,
    date: now,
    address: {
      street: "Hoppe Unions",
      city: "Sharonstead",
      state: "Florida",
      zip: "13652",
    },
  },
  {
    id: "4e0c6c36-85ee-49e1-a51d-69305c368d5a",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 4,
    name: "totam ipsa doloribus",
    accountName: "Pied Piper",
    status: "punch",
    total: 746.00,
    date: now,
    address: {
      street: "Cassin Land",
      city: "Ziemannboro",
      state: "Iowa",
      zip: "73738",
    },
  },
  {
    id: "e2232dfa-7d82-4ce7-8682-20f2ed60840a",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 5,
    name: "lorem ipsum dolor",
    accountName: "Acme Corporation",
    status: "measure",
    total: 1250.00,
    date: now,
    address: {
      street: "Main Street",
      city: "Springfield",
      state: "Illinois",
      zip: "62701",
    }
  },
  {
    id: "f172ecca-d2aa-465a-be99-51e0d68651e2",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 6,
    name: "sit amet consectetur",
    accountName: "Globex Corporation",
    status: "install",
    total: 890.50,
    date: now,
    address: {
      street: "Oak Avenue",
      city: "Riverside",
      state: "California",
      zip: "92501",
    }
  },
  {
    id: "fe7a42e8-a0fa-42ea-bbc4-4789c594da1d",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 7,
    name: "adipiscing elit sed",
    accountName: "Umbrella Corp",
    status: "fabricate",
    total: 2100.75,
    date: now,
    address: {
      street: "Pine Street",
      city: "Portland",
      state: "Oregon",
      zip: "97201",
    }
  },
  {
    id: "f7a2f8f9-a0fa-42ea-bbc4-4789c594da1d",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 8,
    name: "do eiusmod tempor",
    accountName: "Initech",
    status: "punch",
    total: 567.25,
    date: now,
    address: {
      street: "Elm Drive",
      city: "Austin",
      state: "Texas",
      zip: "73301",
    }
  },
  {
    id: "ed354dff-c2e0-4007-9cba-e8b046eb3b08",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 9,
    name: "incididunt ut labore",
    accountName: "Cyberdyne Systems",
    status: "measure",
    total: 1875.00,
    date: now,
    address: {
      street: "Maple Lane",
      city: "Denver",
      state: "Colorado",
      zip: "80201",
    }
  },
  {
    id: "f172ecca-d2aa-465a-be99-51e0d68651e2",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 10,
    name: "sit amet consectetur",
    accountName: "Globex Corporation",
    status: "install",
    total: 890.50,
    date: now,
    address: {
      street: "Oak Avenue",
      city: "Riverside",
      state: "California",
      zip: "92501",
    }
  },
  {
    id: "fe7a42e8-a0fa-42ea-bbc4-4789c594da1d",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 11,
    name: "adipiscing elit sed",
    accountName: "Umbrella Corp",
    status: "fabricate",
    total: 2100.75,
    date: now,
    address: {
      street: "Pine Street",
      city: "Portland",
      state: "Oregon",
      zip: "97201",
    }
  },
  {
    id: "f7a2f8f9-a0fa-42ea-bbc4-4789c594da1d",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 12,
    name: "do eiusmod tempor",
    accountName: "Initech",
    status: "punch",
    total: 567.25,
    date: now,
    address: {
      street: "Elm Drive",
      city: "Austin",
      state: "Texas",
      zip: "73301",
    }
  },
  {
    id: "ed354dff-c2e0-4007-9cba-e8b046eb3b08",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 13,
    name: "incididunt ut labore",
    accountName: "Cyberdyne Systems",
    status: "measure",
    total: 1875.00,
    date: now,
    address: {
      street: "Maple Lane",
      city: "Denver",
      state: "Colorado",
      zip: "80201",
    }
  },
  {
    id: "f172ecca-d2aa-465a-be99-51e0d68651e2",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 14,
    name: "sit amet consectetur",
    accountName: "Globex Corporation",
    status: "install",
    total: 890.50,
    date: now,
    address: {
      street: "Oak Avenue",
      city: "Riverside",
      state: "California",
      zip: "92501",
    }
  }
]

export const mockDataAI: JobInput[] = [
  {
    id: "27672077-d65a-4e1b-af8a-4802bc6a0ec6",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 1,
    name: "cumque dolore et",
    accountName: "Casper LLC",
    status: "measure",
    total: 633.00,
    date: now,
    address: {
      street: "Kacey Meadows",
      city: "Fort Tressieland",
      state: "Alaska",
      zip: "58185",
    },
  },
  {
    id: "a33bab25-f942-4b02-a37c-8f9009fb91cc",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 2,
    name: "corporis laborum non",
    accountName: "Stark Industries",
    status: "install",
    total: 123.00,
    date: now,
    address: {
      street: "Dawson Rest",
      city: "South Finnworth",
      state: "Massachusetts",
      zip: "18135",
    },
  },
  {
    id: "2412370c-c023-43df-9ee1-11dbcf3f15a4",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 3,
    name: "quia eaque quisquam",
    accountName: "Wayne Enterprises",
    status: "fabricate",
    total: 840.00,
    date: now,
    address: {
      street: "Hoppe Unions",
      city: "Sharonstead",
      state: "Florida",
      zip: "13652",
    },
  },
  {
    id: "4e0c6c36-85ee-49e1-a51d-69305c368d5a",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 4,
    name: "totam ipsa doloribus",
    accountName: "Pied Piper",
    status: "punch",
    total: 746.00,
    date: now,
    address: {
      street: "Cassin Land",
      city: "Ziemannboro",
      state: "Iowa",
      zip: "73738",
    },
  },
  {
    id: "8f9e2c45-1234-4567-8901-234567890123",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 5,
    name: "lorem ipsum dolor",
    accountName: "Acme Corporation",
    status: "measure",
    total: 1250.00,
    date: now,
    address: {
      street: "Main Street",
      city: "Springfield",
      state: "Illinois",
      zip: "62701",
    },
  },
  {
    id: "9a8b7c6d-5e4f-3210-9876-543210987654",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 6,
    name: "sit amet consectetur",
    accountName: "Globex Corporation",
    status: "install",
    total: 890.50,
    date: now,
    address: {
      street: "Oak Avenue",
      city: "Riverside",
      state: "California",
      zip: "92501",
    },
  },
  {
    id: "1a2b3c4d-5e6f-7890-abcd-ef1234567890",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 7,
    name: "adipiscing elit sed",
    accountName: "Umbrella Corp",
    status: "fabricate",
    total: 2100.75,
    date: now,
    address: {
      street: "Pine Street",
      city: "Portland",
      state: "Oregon",
      zip: "97201",
    },
  },
  {
    id: "fedcba98-7654-3210-fedc-ba9876543210",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 8,
    name: "do eiusmod tempor",
    accountName: "Initech",
    status: "punch",
    total: 567.25,
    date: now,
    address: {
      street: "Elm Drive",
      city: "Austin",
      state: "Texas",
      zip: "73301",
    },
  },
  {
    id: "11223344-5566-7788-9900-aabbccddeeff",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 9,
    name: "incididunt ut labore",
    accountName: "Cyberdyne Systems",
    status: "measure",
    total: 1875.00,
    date: now,
    address: {
      street: "Maple Lane",
      city: "Denver",
      state: "Colorado",
      zip: "80201",
    },
  },
  {
    id: "aabbccdd-eeff-1122-3344-556677889900",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 10,
    name: "et dolore magna",
    accountName: "Oscorp Industries",
    status: "install",
    total: 945.80,
    date: now,
    address: {
      street: "Cedar Boulevard",
      city: "Phoenix",
      state: "Arizona",
      zip: "85001",
    },
  },
  {
    id: "12345678-90ab-cdef-1234-567890abcdef",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 11,
    name: "aliqua ut enim",
    accountName: "Stark Enterprises",
    status: "fabricate",
    total: 1456.30,
    date: now,
    address: {
      street: "Birch Road",
      city: "Seattle",
      state: "Washington",
      zip: "98101",
    },
  },
  {
    id: "abcdef12-3456-7890-abcd-ef1234567890",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 12,
    name: "ad minim veniam",
    accountName: "LexCorp",
    status: "punch",
    total: 723.45,
    date: now,
    address: {
      street: "Willow Street",
      city: "Miami",
      state: "Florida",
      zip: "33101",
    },
  },
  {
    id: "98765432-10ab-cdef-9876-543210abcdef",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 13,
    name: "quis nostrud exercitation",
    accountName: "Weyland-Yutani",
    status: "measure",
    total: 2890.00,
    date: now,
    address: {
      street: "Aspen Circle",
      city: "Las Vegas",
      state: "Nevada",
      zip: "89101",
    },
  },
  {
    id: "13579bdf-2468-ace0-1357-9bdf2468ace0",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 14,
    name: "ullamco laboris nisi",
    accountName: "Soylent Corp",
    status: "install",
    total: 1234.67,
    date: now,
    address: {
      street: "Poplar Avenue",
      city: "Nashville",
      state: "Tennessee",
      zip: "37201",
    },
  },
  {
    id: "2468ace0-1357-9bdf-2468-ace013579bdf",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 15,
    name: "ut aliquip ex ea",
    accountName: "Tyrell Corporation",
    status: "fabricate",
    total: 3456.78,
    date: now,
    address: {
      street: "Sycamore Street",
      city: "Atlanta",
      state: "Georgia",
      zip: "30301",
    },
  },
  {
    id: "369cf258-147b-0369-cf25-8147b0369cf2",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 16,
    name: "commodo consequat duis",
    accountName: "Massive Dynamic",
    status: "punch",
    total: 876.54,
    date: now,
    address: {
      street: "Hickory Lane",
      city: "Charlotte",
      state: "North Carolina",
      zip: "28201",
    },
  },
  {
    id: "147b0369-cf25-8147-b036-9cf2581470b0",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 17,
    name: "aute irure dolor",
    accountName: "Aperture Science",
    status: "measure",
    total: 1987.65,
    date: now,
    address: {
      street: "Dogwood Drive",
      city: "Salt Lake City",
      state: "Utah",
      zip: "84101",
    },
  },
  {
    id: "258cf147-b036-9cf2-5814-70b0369cf258",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 18,
    name: "in reprehenderit voluptate",
    accountName: "Black Mesa",
    status: "install",
    total: 654.32,
    date: now,
    address: {
      street: "Magnolia Boulevard",
      city: "New Orleans",
      state: "Louisiana",
      zip: "70112",
    },
  },
  {
    id: "789abc12-def4-5678-9abc-123def456789",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 19,
    name: "velit esse cillum",
    accountName: "Vault-Tec",
    status: "fabricate",
    total: 2345.89,
    date: now,
    address: {
      street: "Chestnut Avenue",
      city: "Boston",
      state: "Massachusetts",
      zip: "02101",
    },
  },
  {
    id: "def45678-9abc-123d-ef45-6789abc123de",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 20,
    name: "dolore eu fugiat",
    accountName: "RoboCorp",
    status: "punch",
    total: 1098.76,
    date: now,
    address: {
      street: "Walnut Street",
      city: "Philadelphia",
      state: "Pennsylvania",
      zip: "19101",
    },
  },
  {
    id: "456789ab-c123-def4-5678-9abc123def45",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 21,
    name: "nulla pariatur excepteur",
    accountName: "Skynet",
    status: "measure",
    total: 3210.45,
    date: now,
    address: {
      street: "Pecan Lane",
      city: "Houston",
      state: "Texas",
      zip: "77001",
    },
  },
  {
    id: "c123def4-5678-9abc-123d-ef456789abc1",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 22,
    name: "sint occaecat cupidatat",
    accountName: "Shinra Electric",
    status: "install",
    total: 789.12,
    date: now,
    address: {
      street: "Cypress Drive",
      city: "San Diego",
      state: "California",
      zip: "92101",
    },
  },
  {
    id: "9abc123d-ef45-6789-abc1-23def456789a",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 23,
    name: "non proident sunt",
    accountName: "Abstergo Industries",
    status: "fabricate",
    total: 1567.89,
    date: now,
    address: {
      street: "Redwood Circle",
      city: "San Francisco",
      state: "California",
      zip: "94101",
    },
  },
  {
    id: "6789abc1-23de-f456-789a-bc123def4567",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 24,
    name: "in culpa qui",
    accountName: "Monarch Solutions",
    status: "punch",
    total: 2876.54,
    date: now,
    address: {
      street: "Sequoia Avenue",
      city: "Sacramento",
      state: "California",
      zip: "95814",
    },
  },
  {
    id: "23def456-789a-bc12-3def-456789abc123",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 25,
    name: "officia deserunt mollitia",
    accountName: "Dharma Initiative",
    status: "measure",
    total: 987.65,
    date: now,
    address: {
      street: "Juniper Street",
      city: "Honolulu",
      state: "Hawaii",
      zip: "96813",
    },
  },
  {
    id: "789abc12-3def-4567-89ab-c123def45678",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 26,
    name: "anim id est",
    accountName: "Hanso Foundation",
    status: "install",
    total: 1432.10,
    date: now,
    address: {
      street: "Spruce Lane",
      city: "Anchorage",
      state: "Alaska",
      zip: "99501",
    },
  },
  {
    id: "def45678-9abc-123d-ef45-6789abc123de",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 27,
    name: "laborum et dolorum",
    accountName: "Omni Consumer Products",
    status: "fabricate",
    total: 2654.32,
    date: now,
    address: {
      street: "Fir Boulevard",
      city: "Portland",
      state: "Maine",
      zip: "04101",
    },
  },
  {
    id: "9abc123d-ef45-6789-abc1-23def456789b",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 28,
    name: "fuga nam quam",
    accountName: "Zorg Industries",
    status: "punch",
    total: 876.43,
    date: now,
    address: {
      street: "Hemlock Drive",
      city: "Burlington",
      state: "Vermont",
      zip: "05401",
    },
  },
  {
    id: "123def45-6789-abc1-23de-f456789abc12",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 29,
    name: "nisi ut aliquip",
    accountName: "Gekko & Co",
    status: "measure",
    total: 1765.98,
    date: now,
    address: {
      street: "Cottonwood Avenue",
      city: "Albuquerque",
      state: "New Mexico",
      zip: "87101",
    },
  },
  {
    id: "6789abc1-23de-f456-789a-bc123def4568",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 30,
    name: "ex ea commodo",
    accountName: "Sterling Cooper",
    status: "install",
    total: 1098.76,
    date: now,
    address: {
      street: "Basswood Street",
      city: "Boise",
      state: "Idaho",
      zip: "83702",
    },
  },
  {
    id: "abc123de-f456-789a-bc12-3def456789ab",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 31,
    name: "consequat duis aute",
    accountName: "Prestige Worldwide",
    status: "fabricate",
    total: 2987.54,
    date: now,
    address: {
      street: "Beech Circle",
      city: "Des Moines",
      state: "Iowa",
      zip: "50309",
    },
  },
  {
    id: "9ab0af91-9dc8-42c5-8145-e7a226443e12",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 32,
    name: "irure dolor in",
    accountName: "Dunder Mifflin",
    status: "punch",
    total: 543.21,
    date: now,
    address: {
      street: "Mulberry Lane",
      city: "Scranton",
      state: "Pennsylvania",
      zip: "18503",
    },
  },
  {
    id: "ff784533-1731-43c5-8110-907f6835dd7d",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 33,
    name: "reprehenderit in voluptate",
    accountName: "Sabre Corporation",
    status: "measure",
    total: 1876.43,
    date: now,
    address: {
      street: "Tulip Drive",
      city: "Tallahassee",
      state: "Florida",
      zip: "32301",
    },
  },
  {
    id: "789abc123-def4-5678-9abc-123def456789",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 34,
    name: "velit esse cillum",
    accountName: "Bluth Company",
    status: "install",
    total: 2345.67,
    date: now,
    address: {
      street: "Rose Avenue",
      city: "Newport Beach",
      state: "California",
      zip: "92660",
    },
  },
  {
    id: "123def456-789a-bc12-3def-456789abc124",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 35,
    name: "dolore eu fugiat",
    accountName: "Vandelay Industries",
    status: "fabricate",
    total: 987.32,
    date: now,
    address: {
      street: "Lily Street",
      city: "New York",
      state: "New York",
      zip: "10001",
    },
  },
  {
    id: "789abc123-def4-5678-9abc-123def456790",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 36,
    name: "nulla pariatur excepteur",
    accountName: "Kramerica Industries",
    status: "punch",
    total: 1654.89,
    date: now,
    address: {
      street: "Daisy Lane",
      city: "Jersey City",
      state: "New Jersey",
      zip: "07302",
    },
  },
  {
    id: "456def789-abc1-23de-f456-789abc123def",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 37,
    name: "sint occaecat cupidatat",
    accountName: "Hooli",
    status: "measure",
    total: 2876.54,
    date: now,
    address: {
      street: "Sunflower Boulevard",
      city: "Palo Alto",
      state: "California",
      zip: "94301",
    },
  },
  {
    id: "abc123def-456-789a-bc12-3def456789ab",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 38,
    name: "non proident sunt",
    accountName: "Raviga Capital",
    status: "install",
    total: 1234.56,
    date: now,
    address: {
      street: "Orchid Circle",
      city: "Menlo Park",
      state: "California",
      zip: "94025",
    },
  },
  {
    id: "def456789-abc1-23de-f456-789abc123deg",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 39,
    name: "in culpa qui",
    accountName: "Bachmanity",
    status: "fabricate",
    total: 3456.78,
    date: now,
    address: {
      street: "Violet Avenue",
      city: "San Jose",
      state: "California",
      zip: "95113",
    },
  },
  {
    id: "789abc123-def4-5678-9abc-123def456791",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 40,
    name: "officia deserunt mollitia",
    accountName: "Endframe",
    status: "punch",
    total: 876.54,
    date: now,
    address: {
      street: "Iris Street",
      city: "Mountain View",
      state: "California",
      zip: "94041",
    },
  },
  {
    id: "123def456-789a-bc12-3def-456789abc125",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 41,
    name: "anim id est",
    accountName: "Bro",
    status: "measure",
    total: 1987.65,
    date: now,
    address: {
      street: "Jasmine Lane",
      city: "Cupertino",
      state: "California",
      zip: "95014",
    },
  },
  {
    id: "456789abc-123d-ef45-6789-abc123def456",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    jobNumber: 42,
    name: "laborum et dolorum",
    accountName: "Aviato",
    status: "install",
    total: 2543.21,
    date: now,
    address: {
      street: "Carnation Drive",
      city: "Fremont",
      state: "California",
      zip: "94536",
    },
  },
]
